joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

lwr_control:
  type: stack_of_passive_controllers_controller/StackOfPassiveControllersController
  joints:
    - lwr_a1_joint
    - lwr_a2_joint
    - lwr_e1_joint
    - lwr_a3_joint
    - lwr_a4_joint
    - lwr_a5_joint
    - lwr_a6_joint
  passive_controllers:
    lwr_3_link:
      Wmax: [100., 100., 100., 0.02, 0.02, 0.02]
      Err0: [0.01, 0.01, 0.01, 0.057, 0.057, 0.057]
      Errb: [0.02, 0.02, 0.02, 0.63, 0.63, 0.63]
      K0: [100., 100., 100., 0.02, 0.02, 0.02]
    lwr_6_link:
      Wmax: [5000., 5000., 5000., 25., 25., 25.]
      Err0: [0.01, 0.01, 0.01, 0.057, 0.057, 0.057]
      Errb: [0.02, 0.02, 0.02, 0.63, 0.63, 0.63]
      K0: [5000., 5000., 5000., 25., 25., 25.]
    lwr_7_link:
      Wmax: [50., 50., 50., 5., 5., 5.]
      Err0: [0.01, 0.01, 0.01, 0.057, 0.057, 0.057]
      Errb: [0.02, 0.02, 0.02, 0.63, 0.63, 0.63]
      K0: [10., 10., 10., 5., 5., 5.]
