joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

lwr_control:
  type: stack_of_passive_controllers_controller/StackOfPassiveControllersController
  # type: effort_feedforward_with_joint_feedback_controller/EffortFeedforwardWithJointFeedbackController
  joints:
    - lwr_a1_joint
    - lwr_a2_joint
    - lwr_e1_joint
    - lwr_a3_joint
    - lwr_a4_joint
    - lwr_a5_joint
    - lwr_a6_joint
  passive_controllers:
    # lwr_3_link:
    #   Wmax: [500., 500., 500., 0.2, 0.2, 0.2]
    #   Err0: [0.005, 0.005, 0.005, 0.57, 0.57, 0.57]
    #   Errb: [0.01, 0.01, 0.01, 0.63, 0.63, 0.63]
    #   K0: [20., 20., 20., 0., 0., 0.]
    # lwr_5_link:
    #   Wmax: [500., 500., 500., 0.02, 0.02, 0.02]
    #   Err0: [0.04, 0.04, 0.04, 0.057, 0.057, 0.057]
    #   Errb: [0.05, 0.05, 0.05, 0.63, 0.63, 0.63]
    #   K0: [5., 5., 5., 0., 0., 0.]
    lwr_3_link:
      Wmax: [50., 50., 50., 0.02, 0.02, 0.02]
      Err0: [0.01, 0.01, 0.01, 0.057, 0.057, 0.057]
      Errb: [0.02, 0.02, 0.02, 0.63, 0.63, 0.63]
      K0: [20., 20., 20., 0., 0., 0.]
    lwr_7_link:
      Wmax: [50., 50., 50., 1., 1., 1.]
      Err0: [0.01, 0.01, 0.01, 0.057, 0.057, 0.057]
      Errb: [0.02, 0.02, 0.02, 0.63, 0.63, 0.63]
      K0: [100., 100., 100., 10., 10., 10.]
  # max_efforts: [40., 80., 40., 20., 20., 20.]
